name: CI
on: [push, pull_request]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install emcc compiler
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: latest
          actions-cache-folder: emsdk-cache-${{ matrix.os }}

      - name: Verify emcc install
        run: emcc -v

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Checkout extism/cli
        uses: actions/checkout@v3
        with:
          repository: extism/cli
          path: cli

      - name: Install Extism & CLI
        run: |
          pushd cli
          pip3 install cffi
          pip3 install .
          popd

          extism install git

      - name: Example
        run: |
          cd examples/count-vowels
          TEST=$(make example)
          echo $TEST | grep '"count": 4'
